language: java
jdk:
  - openjdk11
  - openjdk10
before_script:
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_abed99774422_key
  -iv $encrypted_abed99774422_iv -in client-secret.json.enc -out client-secret.json
  -d; else printf "This is a pull request, so no need to decode secret."; fi'
# Don't deploy if a pull request or non oracljdk8 build
script:
- mvn test -B
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_JDK_VERSION}" = "openjdk11" ]; then mvn appengine:update -Dappengine.additionalParams="--service_account_json_key_file=client-secret.json"; else printf "Not deploying\nPull request: $TRAVIS_PULL_REQUEST\nJDK version: $TRAVIS_JDK_VERSION"; fi'
